domain = "https://example.com"
proxy_address = "http://192.168.1.3:8080"
backend_server = "https://shibukawa.github.io/demo"
site_name = "shibu.jp"
site_owner = "Yoshiki Shibukawa"
twitter_id = "@shibu_jp"
facebook_app_id = ""
default_image = ""
document_selectors = ["main"]

[route.top]
    path = "/"
    body_selector = "#root"
    ogp = true
    ssr = true

